replicaCount: 1

image:
  repository: iamruparc/go-web-app
  tag: 26397961425
  pullPolicy: IfNotPresent
  tag: 26397961425


ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        -path: /
        pathType: ImplementationSpecific