name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Verify Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Build application
        run: go build -o go-web-app .

      - name: Run tests
        run: go test ./...

  code-quality:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: code-quality

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.run_id }}

  update-new-tag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update Helm chart with new Docker image tag
        run: |
          NEW_TAG=${{ github.run_id }}
          sed -i "s/tag: .*/tag: ${NEW_TAG}/" helm/go-web-app-chart/values.yaml

      - name: Commit and push changes
        run: |
          NEW_TAG=${{ github.run_id }}

          git config --global user.name "rupam-cx"
          git config --global user.email "rupam.das@codelogicx.com"

          git add helm/go-web-app-chart/values.yaml

          git commit -m "Update Helm chart with new Docker image tag: ${NEW_TAG}" || echo "No changes to commit"

          git push origin main
