name: CI-CD

on:
  push:
    branches:
      - oidc
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Verify Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Build application
        run: go build -o go-web-app .

      - name: Run tests
        run: go test ./...

  code-quality:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: code-quality

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.run_id }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image

    steps:
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::585853585762:role/github-actions-deploy-role
          aws-region: ap-south-1

      - name: Deploy to EC2 using SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Go Web App" \
            --parameters commands='[
              "docker pull ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.run_id }}",
              "docker stop go-web-app || true",
              "docker rm go-web-app || true",
              "docker run -d --name go-web-app -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.run_id }}"
            ]' \
            --region ap-south-1
